### ISSUE TITLE
Git clone url wrong in readme

### ISSUE THREAD

**Issue by BigTarr** [swgemu/Core3#6]
Does this readme have the wrong clone url?
![2022-12-20_09-57-54](https://user-images.githubusercontent.com/19396793/208734441-ad9a5270-379c-435e-9cd0-350d80fe7ea4.png)

 I think it should be: git clone https://github.com/swgemu/Core3.git

**Comment by jordigil** [comment]
I think it's ok, this repo on github is a mirror of the original.

Check: https://review.swgemu.com/gitweb?p=Core3.git;a=summary

**Comment by BigTarr** [comment]
Okay. Interesting, maybe it is just directed me wrong? here is what I got...
http://review.swgemu.com/Core3/

Cloning into 'Core3'...
fatal: unable to access 'http://review.swgemu.com/Core3/': The requested URL returned error: 504

**Comment by BigTarr** [comment]
I was able to clone it though with:
ubuntu-linux-20-04-desktop:~/git$ git clone https://github.com/swgemu/Core3.git
Cloning into 'Core3'...
remote: Enumerating objects: 487859, done.
remote: Counting objects: 100% (1537/1537), done.
remote: Compressing objects: 100% (494/494), done.
remote: Total 487859 (delta 1209), reused 1298 (delta 1040), pack-reused 486322
Receiving objects: 100% (487859/487859), 240.50 MiB | 26.00 MiB/s, done.
Resolving deltas: 100% (426648/426648), done.
Updating files: 100% (30204/30204), done.

**Comment by Hakry** [comment]
Nothing is wrong with the the URL. We use Gerrit (review.swgemu.com) for our workflow.
