### ISSUE TITLE
Error building Core3 at 98% (Ubuntu 16.04): call of overloaded is ambiguous

### ISSUE THREAD

**Issue by matthew1smith** [swgemu/Core3#7]
This was from my separate Linux server so I had to retype it all up.  New to Linux.  Will try to learn how to save this as a dump on a USB device through terminal in future.  This is from cloning https://github.com/swgemu/Core3/ as the URL in the guide didn't work.  Not currently using Gerrit.

In file included from /home/nonroot/git/Core3/MMOCoreORB/src/server/zone/objects/creature/commands/PurchaseTicketCommand.h:13:0,
from /home/nonroot/git/Core3/MMOCoreORB/src/server/zone/managers/objectcontroller/command/CommandConfigManager3.cpp:146:/home/nonroot/git/Core3/MMOCoreORB/src/server/zone/objects/player/sui/callbacks/TravelCouponUseSuiCallback.h: In member function 'virtual void TravelCouponUseSuiCallBack::run(server::zone::objects::creature::CreatureObject*, server::zone::objects::player::sui::SuiBox*, sys::util::Vector<sys::lang::UnicodeString>*)':
/home/nonroot/git/Core3/MMOCoreORB/src/server/zone/objects/player/sui/callbacks/TravelCouponUseSuiCallback.h:110:59: error: call of overloaded 'TransactionLog(server::zone::objects::creature::CreatureObject*&, TrxCode, bool)' is ambiguous
TransactionLog trx(player, TrxCode::TRAVELSYSTEM, false);
                                                                                          ^
In file included from /home/nonroot/git/Core3/MMOCoreORB/src/server/zone/managers/resource/resourcespawner/ResourceSpawner.h:18:0,
from /home/nonroot/git/Core3/MMOCoreORB/src/autogen/server/zone/managers/resource/ResourceManager.h:103,
from /home/nonroot/git/Core3/MMOCoreORB/src/server/zone/managers/objectcontroller/command/CommandConfigManager3.cpp:16:
/home/nonroot/git/Core3/MMOCoreORB/src/server/zone/objects/transaction/TransactionLog.h:172:2: note: candidate: TransactionLog::TransactionLog(server::zone::objects::scene::SceneObject*, TrxCode, uint, bool, const char*, const char*, int)
TransactionLog(SceneObject* src, TrxCode code, SceneObject* subject, bool exportSubject = false, CAPTURE_CALLER_DECLARE)
^
/home/nonroot/git/Core3/MMOCoreORB/src/server/zone/objects/transaction/TransactionLog.h:161:2: note: candidate: TransactionLog::TransactionLog(server::zone::objects::scene::SceneObject*, TrxCode, server::zone::objects::scene::SceneObject*, bool, const char*, int)
TransactionLog(SceneObject* src, TrxCode code, SceneObject* subject, bool exportSubject = false, CAPTURE_CALLER_DECLARE)
^
src/CMakeFiles/core3.dir/build.make:11870: recipe for target 'src/CMakeFiles/core3.dir/server/zone/managers/objectcontroller/command/CommandConfigManager3.cpp.o' failed
make[3]: *** [src/CMakeFiles/core3.dir/server/zone/managers/objectcontroller/command/CommandConfigManager3.cpp.o] Error 1

**Comment by Hakry** [comment]
Please make sure you have all the proper dependencies and are building properly. There is a guide that is based on Ubuntu 20 that could be used to ensure that or assist in any missed steps. I have not confirmed building on Ubuntu 16, but there are no issues building Core3/unstable.

https://docs.google.com/document/d/1ayaXlaPzBk_5DJcGouSzmTEDQdHN8ZiZ6mfnh8ThLqo/edit

**Comment by matthew1smith** [comment]
EDIT: I see additional dependencies in that Google Doc not listed in the command code provided on the Core3 GitHub page.  I'll try installing those extra ones and rebuilding.

Original reply: Strange.  I'm running it on Ubuntu 16.04 as it was the minimum recommended on the Core3 page.  As for dependencies, I ran as per the guide there:
sudo apt install build-essential libmysqlclient-dev liblua5.3-dev libdb5.3-dev libssl-dev cmake git default-jre

Also had to install Boost as it wasn't installed.  Were there other dependencies beyond those?  If it helps, I'm running Ubuntu Server 16.04 with the standard utilities, not as a VM in Windows.

**Comment by algebuckina** [comment]
https://www.swgemu.com/forums/showthread.php?t=236411
and
sudo apt install build-essential libmysqlclient-dev liblua5.3-dev libdb5.3-dev libssl-dev cmake git default-jre libboost-system-dev libboost-thread-dev libboost-program-options-dev libboost-test-dev mariadb-server
The setup is the same on bare metal cause I've personally done it on an old Dell server running ubuntu server

**Comment by matthew1smith** [comment]
> 

Thanks for the link and commands.  I'm upgrading to 20.04 at the moment as some of the packages that were required from Hakry's document weren't supported by 16.04 - it couldn't find some of them when running sudo apt install.  Will go from there and use that forum link.  Thanks to you both.  I'll use the forums from here since it's not to do with the code.  I'd been following all steps fine but apparently the commands in the readme for Core3 are outdated since it differs to the Word document and that link you shared.  It also says 16.04+ is supported but 20.04+ is required in the Word document.
